package os.com.constant

import org.joda.time.DateTimeZone

object Tags {
    const val birthday = "birthday"
    const val social_id = "social_id"
    const val payment_mode = "payment_mode"
    const val IS_SHOW_WELCOME = "IS_SHOW_WELCOME"
    //    val timeZone = DateTimeZone.UTC!!
    const val Heena = "Heena"
    const val URL = "URL"
    const val CHAT = "CHAT"
    const val TEST = "test"
    const val FCM = "FCM"
    const val ERROR = "error"
    const val PREF = "pref"
    const val GCM = "GCM"
    const val GCMtoken = "GCMtoken"
    const val country_code = "country_code"
    const val USER_DATA = "userData"
    const val DATA = "data"
    const val LAT = "lat"
    const val LNG = "lng"
    const val auth_token = "auth_token"
    const val auth_key = "auth_key"
    const val primary_address = "primary_address"
    const val STORE = "STORE"
    const val vehicle_number = "vehicle_number"
    const val country = "country"
    const val location = "location"
    const val status = "status"
    const val exception = "exception"
    const val message = "message"
    const val FILE = "FILE"
    const val response = "response"
    const val modified = "modified"
    const val confirm_password = "confirm_password"
    const val FCMtoken = "FCMtoken"
    const val LANGUAGE_ARABIC = "ara"
    const val LANGUAGE_ENGLISH = "en"
    const val notification_id = "notification_id"
    const val DATE = "DATE"
    const val DATABASE = "DATABASE"
    const val RESULT = "RESULT"
    const val INTERNET = "INTERNET"
        val timeZone= DateTimeZone.UTC!!
    const val device_type="Android"
    const val first_name = "first_name"
    const val last_name = "last_name"
    const val email = "email"
    const val id = "id"
    const val name = "name"
   const val isLogin="isLogin"
    const val user_id="user_id"
    const val language="language"
    const val match_id="match_id"
    const val contest_id="contest_id"
    const val series_id="series_id"
    const val local_team_id="local_team_id"
    const val visitor_team_id="visitor_team_id"
    const val JoinContestDialog="JoinContestDialog"
    const val password="password"
    const val old_password="old_password"
    const val date_of_birth="date_of_birth"
    const val mobile="mobile"
    const val address="address"
    const val city="city"
    const val state="state"
    const val pincode="pincode"
    const val gender="gender"

}

